# Generated by Django 5.2.4 on 2025-07-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_unik', models.CharField(blank=True, max_length=12, unique=True)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('nomor_tujuan', models.CharField(max_length=20)),
                ('metode_pembayaran', models.CharField(choices=[('dana', 'DANA'), ('ovo', 'OVO'), ('gopay', 'GoPay'), ('shopeepay', 'ShopeePay')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('gagal', 'Gagal')], default='pending', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produk')),
            ],
        ),
    ]
