# Generated by Django 5.2.4 on 2025-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='alamat',
            field=models.TextField(default='Alamat belum diisi'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='jumlah',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
